### PR TITLE
Binance Implementation

### PR DESCRIPTION
**Pull request by hbwhyte**
Finished implementation of the Binance exchange. 

Includes JSON responses, and all 6 core functionalities:

- Connecting successfully to API (Configuration -> BinanceUtil)
- Ticker Info (Services -> BinanceTicker)
- Account balance (Services -> BinanceAccount)
- Withdraw Funds (Services -> BinanceAccount)
- Get Deposit Address to add funds (Services -> BinanceAccount)
- Execute Trade (Services -> BinanceTradeImpl)

It also includes the ability to cancel an order after it has been placed  (Services -> BinanceTradeImpl)

You can test all of those via the endpoints in ExchangeController

If you need my API info let me know.

### CODE REVIEW

**Comment by hbwhyte** [comment]
In order to resolve the Binance dependency you need to do the following:

You need to build the maven artifact yourself.

1) clone this git repo
2) change to the directory
3) issue a mvn install

```
git clone https://github.com/binance-exchange/binance-java-api.git
cd binance-java-api
mvn install
```

After that the dependency can be resolved through you local maven repository.

**Review by Zaytt — APPROVED** [review]

**Review by mattbelsky — APPROVED** [review]
Looks good. Kind of curious why you chose to use @QueryParam instead of @RequestParam (for some reason this always shows as lowercase here) in your controller.

**Comment by hbwhyte** [comment]
@mattbelsky  `@QueryParam` is functionally equivalent in this case, but I can switch to `@RequestParam` (which is the Spring specific annotation) for continuity

**Comment by mattbelsky** [comment]
No need to change anything. I was just curious, that's all.

**Pull request merged**
