### PR TITLE
OAuth2 Client Credentials Grant

### PR DESCRIPTION
**Pull request by ghost**
The Komodo API is technically a resource server that is secured by OAuth2. Clients are able to register with the Authorization Server and obtain access tokens to make calls to secured endpoints of the Komodo API Resource. A client can be any third-party that wants to use the API and eventually the Komodo MVC will be a client.

I wrote instructions in the readme for deploying and testing as a third-party. I’m going to make user registration for the Komodo MVC next and have the MVC application interact with the Komodo API as a client. Also no hibernate needed so far 🙂

### CODE REVIEW

**Comment by hbwhyte** [comment]
Was able to successfully run the program and hit all 3 security endpoints in the readme. Overall looks good to merge :+1: 

One thing that might cause problems once we have a shared database though is that once you create "third-party" once, it's a shared resource. Do we want to have an autoincrementing user id instead?

Also, once the functionality is more built out we can add more detail to the exception (e.g. client could not be created because they already exist in the db; client could not be created because of incomplete/problematic information in the message body)

**Comment by ghost** [comment]
It was intended that everyone makes up their own client_id instead of using "third-party". I could potentially create a method that assigns our own client_id and client_secret when registering to avoid duplicates, but I don't think I can change the field to autoincrementing. Spring Security seems pretty specific about the oauth_client_details table. 

Also, I can add more/better exception handling in a future PR.

**Comment by hbwhyte** [comment]
Ahh that makes sense :) Could we add in the instructions to make client ID be their email? Automatic unique identifier.

**Review by hbwhyte — APPROVED** [review]
I made my comments in the main thread, but now just realized there is a specific "review changes" function :)

**Review by Zaytt — APPROVED** [review]
Same a Heather, was able to to hit the 3 endpoints. Seems all good to me.

**Pull request merged**
